import Head from "next/head";
import Header from "../components/Navbar";
import hero from "../assets/image-hero.jpg";
import Image from "next/image";
import NewProduct from "../components/NewProduct";
import ProductInfo from "../components/ProductInfo";
import chevron from "../assets/shared/desktop/icon-arrow-right.svg";

import headphonesImage from "../assets/shared/desktop/image-category-thumbnail-headphones.png";

export default function Home({ data }: { data: IData[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          sizes="32x32"
          type="image/png"
          href="/assets/favicon-32x32.png"
        />
        <title>Frontend Mentor | Audiophile e-commerce website</title>
      </Head>
      <main>
        <div className="relative grid w-full grid-cols-2">
          <Image
            src={hero}
            alt="hero"
            className="relative col-span-2 mx-auto w-full"
          />
          <div className="absolute col-start-1 col-end-2 grid h-full w-full items-center justify-center align-middle">
            <section className="w-[400px] text-white">
              {data[3].new && (
                <div className="text-sm opacity-50">NEW PRODUCT</div>
              )}
              <div className="my-5 text-6xl">{data[3].name}</div>
              <div className="w-11/12 text-base opacity-75">
                Experience natural, lifelike audio and exceptional build quality
                made for the passionate music enthusiast
              </div>
              <button className="h-12 w-40 bg-primary text-sm font-bold">
                SEE PRODUCT
              </button>
            </section>
          </div>
        </div>
        <div className="mx-auto flex max-w-[1110px] flex-wrap gap-4">
          <div className="relative flex h-[284px] w-[350px] flex-col items-center justify-center ">
            <div className="absolute bottom-0 z-0 h-[204px] w-full rounded-lg bg-[#f1f1f1]"></div>
            <Image
              src={headphonesImage}
              width={200}
              // height={260}
              alt="headphones"
              className="z-10"
            />
            <div className="z-10 mb-4 text-lg font-bold">HEADPHONES</div>
            <div className="relative flex gap-3">
              <div className="mb-4 opacity-50">SHOP </div>
              <div className="mb-4 flex items-center">
                <Image src={chevron} alt="chevron" className="relative" />
              </div>
            </div>
          </div>
          <div className="h-52 w-[350px]">box</div>
          <div className="h-52 w-[350px]">box</div>
        </div>
      </main>
    </>
  );
}

import DATA from "../data.json";
import IData from "../types/data";
export async function getServerSideProps() {
  const data = DATA as unknown as IData;

  // Pass data to the page via props
  return { props: { data } };
}
